create table MONEY_POOL_CTL(
    ID              INT NOT NULL AUTO_INCREMENT,
    NAME            VARCHAR(128),
    TARGET_AMOUNT   FLOAT,
    CURRENT_AMOUNT  FLOAT,
    POOL_DESC       TEXT,
    CRETED_DATE     TIMESTAMP DEFAULT NOW(),
    ENABLE          VARCHAR(1) DEFAULT 'Y',
    PRIMARY KEY(ID)
);
