create table TRADE_TYPE_CTL(
    TRADE_TYPE_ID   VARCHAR(10),
    TRADE_TYPE_NAME VARCHAR(64),
    TRADE_TYPE_DESC TEXT,
    CREATED_DATE    TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY(TRADE_TYPE_ID)
);
